module.exports = {
  errorWords: [
    'sponge bob',
    'ninja turtle',
    'alicia',
    'pizza',
    'peperoni',
    'mouse',
    'anita no lava la tina',
    'microphone',
    'some day i will get everything',
  ],
  singleWords: [
    'Anna',
    'civic',
    'kayak',
    'level',
    'madam',
    'mom',
    'noon',
    'racecar',
    'radar',
    'redder',
    'refer',
    'repaper',
    'rotator',
    'rotor',
    'sagas',
    'solos',
    'stats',
    'tenet',
    'wow',
    'ana',
    'aba',
    'aa',
    'aaa',
    'aaaaa',
  ],
  sentences: ['anita lava la tina'],
};
